### ISSUE TITLE
error: TODO: Implement binary operation for big integers

### ISSUE THREAD

**Issue by flash1293** [zig-wasm/zigc-wasm#1]
Trying to compile the following code works fine with using zigc on Mac, but fails using zigc-wasm:
```
const Place = struct { lat: f32, long: f32 };
const std = @import("std");

pub fn main() !void {
    const x = Place{
        .lat = 51.23423,
        .long = 5.23423,
    };

    var buf: [100]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buf);
    var string = std.ArrayList(u8).init(fba.allocator());
    _ = try std.json.stringify(x, .{}, string.writer()); 
    std.debug.print("{s}\n", .{string.items});
}
```

Gives the error `/lib/std/fmt/errol.zig:301:1: error: TODO: Implement binary operation for big integers: 'rem'`

I'm an absolute beginner in zig, this _might_ be caused by the `only_core_functionality` flag? https://github.com/Afirium/zigc-wasm/blob/main/zig/0.11.x.patch#L22

**Comment by Afirium** [comment]
Hi @flash1293, 

If we take a closer look at how code generation (`codegen`) works for Zig 0.11.0 when targeting WASM, you'll notice that certain operations for `BigInt` (including float types) are not yet implemented:  
- `rem`  
- `and`  
- `or` 

We can confirm this by replacing the float types with u32, for example:
```zig
.lat = 51,
.long = 5,
```
In that case, the example will compile and work as expected:
![image](https://github.com/user-attachments/assets/27e6402f-dbf7-4d00-bfbb-34464f41b2b4)

Here are the relevant links:  
- **Zig 0.11.0**: [[source](https://sourcegraph.com/github.com/ziglang/zig@0.11.x/-/blob/src/arch/wasm/CodeGen.zig?L2657-2702)](https://sourcegraph.com/github.com/ziglang/zig@0.11.x/-/blob/src/arch/wasm/CodeGen.zig?L2657-2702)  
- **Zig master (0.14.0.dev)**: [[source](https://sourcegraph.com/github.com/ziglang/zig/-/blob/src/arch/wasm/CodeGen.zig?L2694-2697)](https://sourcegraph.com/github.com/ziglang/zig/-/blob/src/arch/wasm/CodeGen.zig?L2694-2697)  

In theory, you could download the Zig 0.11.0 source code, apply my Git patch, and then manually add support for the `rem` operation in the codegen for WASM. That should resolve the issue.

**Comment by flash1293** [comment]
Awesome, thanks for the answer, @Afirium !
